BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        size_hint_y: 3
        Button:
            size_hint_x: 1
            text:"size hint x 1"
        Button:
            size_hint_x: 2 
            text:"size hint x 2"
        Button:
            size_hint_x: 3
            text:"size hint x 3"
    BoxLayout:
        size_hint_y: 1
        Button:
            size_hint_x: 1
        Button:
            size_hint_x: 0.75
        Button:
            size_hint_x: 0.25

